[package]
name = "bindings-test"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.0.0" }
desmos-bindings = { path = "../bindings", version = "1.0.0"}
test-contract = { path = "../../contracts/test-contract", version = "1.0.0"}
serde = "1.0.136"
serde_json = "1.0.79"
base64 = "0.13.0"

