name: Desmos Bindings
# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml

on:
  pull_request:

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Verify .rs or toml files ğŸ‘€
        uses: technote-space/get-diff-action@v6.1.0
        id: git_diff
        with:
          PATTERNS: |
            **/**.rs
            **/**.toml
            **/Cargo.lock
          FILES: |
            Cargo.lock

      - name: Setup Rust âš™
        if: env.GIT_DIFF
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.61.0
          profile: minimal
          override: true

      - name: Prepare rust cache ğŸ—„ï¸
        if: env.GIT_DIFF
        uses: Swatinem/rust-cache@v2

      - name: Unit tests ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo unit-test --locked
        env:
          RUST_BACKTRACE: 1

  coverage:
    name: Upload coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Verify .rs files ğŸ‘€
        uses: technote-space/get-diff-action@v6.1.0
        id: git_diff
        with:
          PATTERNS: |
            **/**.rs

      - name: Setup Rust âš™
        if: env.GIT_DIFF
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.61.0
          override: true

      - name: Prepare rust cache ğŸ—„ï¸
        if: env.GIT_DIFF
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-tarpaulin âš™
        if: env.GIT_DIFF
        run: cargo install cargo-tarpaulin

      - name: Generate coverage report ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo tarpaulin --avoid-cfg-tarpaulin --all-features --out xml
        env:
          RUST_BACKTRACE: 1

      - name: Upload coverage ğŸ“¤
        if: env.GIT_DIFF
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/bindings/cobertura.xml

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Verify .rs files ğŸ‘€
        uses: technote-space/get-diff-action@v6.1.0
        id: git_diff
        with:
          PATTERNS: |
            **/**.rs

      - name: Setup Rust âš™
        if: env.GIT_DIFF
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.61.0
          override: true
          components: rustfmt, clippy

      - name: Prepare rust cache ğŸ—„ï¸
        if: env.GIT_DIFF
        uses: Swatinem/rust-cache@v2

      - name: Run cargo fmt âœ…
        if: env.GIT_DIFF
        run: cargo fmt --all -- --check

      - name: Run cargo clippy âœ…
        if: env.GIT_DIFF
        run: cargo clippy

  build:
    name: Test features build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Verify .rs and toml files ğŸ‘€
        uses: technote-space/get-diff-action@v6.1.0
        id: git_diff
        with:
          PATTERNS: |
            **/**.rs
            **/**.toml

      - name: Setup Rust âš™
        if: env.GIT_DIFF
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.61.0
          override: true
          components: rustfmt, clippy

      - name: Prepare rust cache ğŸ—„ï¸
        if: env.GIT_DIFF
        uses: Swatinem/rust-cache@v2

      - name: Build No features ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features

      - name: Build feature (query) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features query

      - name: Build feature (profiles) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features profiles

      - name: Build feature (profiles+query) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features profiles,query

      - name: Build feature (subspaces) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features subspaces

      - name: Build feature (subspaces+query) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features subspaces,query

      - name: Build feature (relationships) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features relationships

      - name: Build feature (relationships+query) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features relationships,query

      - name: Build feature (posts) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features posts

      - name: Build feature (posts+query) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features posts,query

      - name: Build feature (reactions) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features reactions

      - name: Build feature (reactions+query) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features reactions,query

      - name: Build feature (reports) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features reports

      - name: Build feature (reports+query) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features reports,query

      - name: Build feature (msg) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features msg

      - name: Build feature (msg+profiles) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features msg,profiles

      - name: Build feature (msg+relationships) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features msg,relationships

      - name: Build feature (msg+subspaces) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features msg,subspaces

      - name: Build feature (msg+posts) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features msg,posts

      - name: Build feature (msg+reactions) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features msg,reactions

      - name: Build feature (msg+reports) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features msg,reports
      
      - name: Build feature (mocks) ğŸ§ª
        if: env.GIT_DIFF
        working-directory: ./packages/bindings
        run: cargo build --no-default-features --features mocks
